services:
  db:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=foyer
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - $PWD/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql


  spring_app:
    container_name: foyer-app
    image: foyer-app:latest
    restart: on-failure
    build: .
    ports:
      - 8081:8081
    depends_on:
      db


volumes:
  mysql:
    driver: local

