services:
  db:
    container_name: mysql
    image: mysql:9.2.0
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=foyer
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - $PWD/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql


  spring_app:
    container_name: foyer-app
    image: foyer-app:latest
    restart: on-failure
    build: .
    ports:
      - 8081:8081
    depends_on:
      - db
    command: ["./wait-for-db.sh", "java", "-jar", "your-spring-app.jar"]

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - spring_app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=211JFT9368
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DATASOURCES_DEFAULT_TYPE=prometheus
      - GF_DATASOURCES_DEFAULT_URL=http://localhost:9090
      - GF_DATASOURCES_DEFAULT_ACCESS=proxy
      - GF_DATASOURCES_DEFAULT_IS_DEFAULT=true
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus




volumes:
  grafana-data:
  mysql:
    driver: local



