pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'samarelfidha/alpine:latest'
        DOCKER_CREDENTIALS_ID = 'samar-PAT'
        GIT_CREDENTIALS_ID = 'PAT-SAMAR'
        ARTIFACT_NAME = 'Foyer-0.0.1-SNAPSHOT.jar'
        GROUP_ID = 'tn/esprit/spring'
        ARTIFACT_VERSION = '0.0.1-SNAPSHOT'
        SONAR_HOST_URL = 'http://your-sonarqube-url' // Remplacez par l'URL de votre SonarQube
        SONAR_CREDENTIALS_ID = 'sonar-credentials-id' // Remplacez par l'ID de vos informations d'identification SonarQube
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo 'Checking out the code...'
                git branch: 'main',
                    url: 'https://github.com/samarFidha/devops.git',
                    credentialsId: GIT_CREDENTIALS_ID
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo 'Running SonarQube analysis...'
                script {
                    withCredentials([usernamePassword(credentialsId: SONAR_CREDENTIALS_ID, passwordVariable: 'SONAR_PASSWORD', usernameVariable: 'SONAR_USERNAME')]) {
                        sh "mvn sonar:sonar -Dsonar.host.url=${SONAR_HOST_URL} -Dsonar.login=${SONAR_USERNAME} -Dsonar.password=${SONAR_PASSWORD}"
                    }
                }
            }
        }

        stage('Build with Maven') {
            steps {
                echo 'Building the Maven project...'
                sh 'mvn clean package'
                sh 'ls -l target/'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                dir('docker') { // Utilisez dir pour exécuter dans le dossier docker
                    sh 'ls -l'
                    sh "docker build -t ${DOCKER_IMAGE} ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                echo 'Pushing Docker image to Docker Hub...'
                script {
                    withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS_ID, passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                        sh 'echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin'
                        sh "docker push ${DOCKER_IMAGE}"
                    }
                }
            }
        }

        stage('Deploy Container') {
            steps {
                echo 'Deploying the container...'
                sh 'docker stop springboot-app || true'
                sh 'docker rm springboot-app || true'
                sh "docker run -d -p 8081:8080 --name springboot-app ${DOCKER_IMAGE}"
            }
        }

        stage('Nexus') {
            steps {
                echo 'Configuring Nexus...'
                sh 'mvn clean'
                sh 'mvn package -DskipTests'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs.'
        }
    }
}